### ISSUE TITLE
Request: Option to not automatically make keymaps

### ISSUE THREAD

**Issue by wbthomason** [pechorin/any-jump.nvim#3]
I would prefer to set my own global keybindings for this plugin. It would be helpful if there was a configuration variable to determine whether or not the plugin makes the default keybindings for a user.

**Comment by pechorin** [comment]
@wbthomason you talk only about global key mappings? not about local buffer popup window?

**Comment by pechorin** [comment]
For now i'm a little confusing about implementation.

Where are to ways:

1. user should explicitly set all keybindings in config by self
2. user should add `let g:any_jump_skip_default_keybindings` and explicitly add keybinds, otherwise default will be set
3. User can explicitly call `call g:AnyJumpSetupKeybinds()` (maybe with provided key configs for overriding defaults), otherwise no keybindings will set

Maybe also i should recheck i where is any already binded commands to `<leader>j` and if none then setup defaults.

The big area to think. I will to other plugins strategies.

**Comment by pechorin** [comment]
@wbthomason fixed in https://github.com/pechorin/any-jump.nvim/commit/b8e30768475dac224ae983649ab9368b34eaadb3

so you can do

```viml
let g:any_jump_disable_default_keybindings = v:true
```

And write you own :) (for now)

**Comment by wbthomason** [comment]
@pechorin: Great, thank you! This is basically what I was after. It would be nice to be able to disable/customize the keybindings in the pop-up window as well, but that is (for me) much less of a concern. Thank you for the rapid response!
